name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' 

      - name: Install dependencies
        run: npm install 

      - name: Use environment variables
        run: |
          echo "Username: ${{ secrets.USERNAME }}"
          echo "Password: ${{ secrets.PASSWORD }}"
          echo "Xiaolin: ${{ secrets.XIAOLIN }}"
          echo "Admin: ${{ secrets.ADMIN }}"

      - name: Run tests
        run: npm test 
